name: journal_mobile_api
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.6.12
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  shared_preferences: ^2.3.2
  intl: ^0.18.1
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
