// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6VL571dwa4hj06Ed0LoWPIE5Zag6oxkk',
    appId: '1:983298776227:android:accc28cdf0c6ef411a3316',
    messagingSenderId: '983298776227',
    projectId: 'flutter-firebase-39aa1',
    storageBucket: 'flutter-firebase-39aa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOmCsrgadW1Qnxy5pN9L-LHhtOfChep-w',
    appId: '1:983298776227:ios:e39f65981287b26f1a3316',
    messagingSenderId: '983298776227',
    projectId: 'flutter-firebase-39aa1',
    storageBucket: 'flutter-firebase-39aa1.firebasestorage.app',
    iosBundleId: 'com.example.journalMobileApi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2MClNnlyzPA1qZ1NFk93h7QMp7mhVR-4',
    appId: '1:983298776227:web:f7db53e2f18cb5ca1a3316',
    messagingSenderId: '983298776227',
    projectId: 'flutter-firebase-39aa1',
    authDomain: 'flutter-firebase-39aa1.firebaseapp.com',
    storageBucket: 'flutter-firebase-39aa1.firebasestorage.app',
    measurementId: 'G-Y8TDPQTKCX',
  );

}